config/routes.rb
Projekt::Application.routes.draw do
  resources :wydarzenies

  resources :kategoria

  resources :komentarzs

  resources :wpis

  resources :uzytkowniks

end

app/models/komentarz.rb
class Komentarz < ActiveRecord::Base
  belongs_to :uzytkownik
  attr_accessible :tresc, :uzytkownik
end

app/controllers/komentarzs_controller.rb
class KomentarzsController < ApplicationController
  before_filter :find_uzytkowniks, :only => [:new, :edit, :update, :create]
  # GET /komentarzs
  # GET /komentarzs.json
  def index
    @komentarzs = Komentarz.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @komentarzs }
    end
  end

  # GET /komentarzs/1
  # GET /komentarzs/1.json
  def show
    @komentarz = Komentarz.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @komentarz }
    end
  end

  # GET /komentarzs/new
  # GET /komentarzs/new.json
  def new
    @komentarz = Komentarz.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @komentarz }
    end
  end

  # GET /komentarzs/1/edit
  def edit
    @komentarz = Komentarz.find(params[:id])
  end

  # POST /komentarzs
  # POST /komentarzs.json
  def create
    @komentarz = Komentarz.new(params[:komentarz])

    respond_to do |format|
      if @komentarz.save
        format.html { redirect_to @komentarz, notice: 'Komentarz was successfully created.' }
        format.json { render json: @komentarz, status: :created, location: @komentarz }
      else
        format.html { render action: "new" }
        format.json { render json: @komentarz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /komentarzs/1
  # PUT /komentarzs/1.json
  def update
    @komentarz = Komentarz.find(params[:id])

    respond_to do |format|
      if @komentarz.update_attributes(params[:komentarz])
        format.html { redirect_to @komentarz, notice: 'Komentarz was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @komentarz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /komentarzs/1
  # DELETE /komentarzs/1.json
  def destroy
    @komentarz = Komentarz.find(params[:id])
    @komentarz.destroy

    respond_to do |format|
      format.html { redirect_to komentarzs_url }
      format.json { head :no_content }
    end
  end
  protected
    def find_uzytkowniks
      @uzytkowniks = Uzytkownik.find(:all).map do |uzytkownik|
        [ uzytkownik.login, uzytkownik ]
      end
    end
end

app/helpers/komentarzs_helper.rb
module KomentarzsHelper
end

app/views/komentarzs/_form.html.erb
<%= form_for(@komentarz) do |f| %>
  <% if @komentarz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@komentarz.errors.count, "error") %> prohibited this komentarz from being saved:</h2>

      <ul>
      <% @komentarz.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :tresc %><br />
    <%= f.text_area :tresc %>
  </div>
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/komentarzs/edit.html.erb
<h1>Editing komentarz</h1>

<%= render 'form' %>

<%= link_to 'Show', @komentarz %> |
<%= link_to 'Back', komentarzs_path %>

app/views/komentarzs/index.html.erb
<h1>Listing komentarzs</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Tresc</th>
    <th>Autor</th>
    <th></th>
    <th></th>
  </tr>

<% @komentarzs.each do |komentarz| %>
  <tr>
    <td><%= komentarz.id %></td>
    <td><%= komentarz.tresc %></td>
    <td><%= komentarz.uzytkownik %></td>
    <td><%= link_to 'Show', komentarz %></td>
    <td><%= link_to 'Edit', edit_komentarz_path(komentarz) %></td>
    <td><%= link_to 'Destroy', komentarz, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Komentarz', new_komentarz_path %>

app/views/komentarzs/new.html.erb
<h1>New komentarz</h1>

<%= render 'form' %>

<%= link_to 'Back', komentarzs_path %>

app/views/komentarzs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @komentarz.id %>
</p>

<p>
  <b>Tresc:</b>
  <%= @komentarz.tresc %>
</p>
<p>
  <b>Autor:</b>
  <%= @komentarz.uzytkownik %>
</p>


<%= link_to 'Edit', edit_komentarz_path(@komentarz) %> |
<%= link_to 'Back', komentarzs_path %>