config/routes.rb
Projekt::Application.routes.draw do
  resources :wydarzenies

  resources :kategoria

  resources :komentarzs

  resources :wpis

  resources :uzytkowniks

end

app/controllers/wydarzenies_controller.rb
class WydarzeniesController < ApplicationController
  before_filter :find_uzytkowniks, :only => [:new, :edit, :update, :create]
  # GET /wydarzenies
  # GET /wydarzenies.json
  def index
    @wydarzenies = Wydarzenie.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wydarzenies }
    end
  end

  # GET /wydarzenies/1
  # GET /wydarzenies/1.json
  def show
    @wydarzeny = Wydarzenie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wydarzeny }
    end
  end

  # GET /wydarzenies/new
  # GET /wydarzenies/new.json
  def new
    @wydarzeny = Wydarzenie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wydarzeny }
    end
  end

  # GET /wydarzenies/1/edit
  def edit
    @wydarzeny = Wydarzenie.find(params[:id])
  end

  # POST /wydarzenies
  # POST /wydarzenies.json
  def create
    @wydarzeny = Wydarzenie.new(params[:wydarzeny])

    respond_to do |format|
      if @wydarzeny.save
        format.html { redirect_to @wydarzeny, notice: 'Wydarzenie was successfully created.' }
        format.json { render json: @wydarzeny, status: :created, location: @wydarzeny }
      else
        format.html { render action: "new" }
        format.json { render json: @wydarzeny.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wydarzenies/1
  # PUT /wydarzenies/1.json
  def update
    @wydarzeny = Wydarzenie.find(params[:id])

    respond_to do |format|
      if @wydarzeny.update_attributes(params[:wydarzeny])
        format.html { redirect_to @wydarzeny, notice: 'Wydarzenie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wydarzeny.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wydarzenies/1
  # DELETE /wydarzenies/1.json
  def destroy
    @wydarzeny = Wydarzenie.find(params[:id])
    @wydarzeny.destroy

    respond_to do |format|
      format.html { redirect_to wydarzenies_url }
      format.json { head :no_content }
    end
  end

protected
    def find_uzytkowniks
      @uzytkowniks = Uzytkownik.find(:all).map do |uzytkownik|
        [ uzytkownik.login, uzytkownik ]
      end
    end

end

app/helpers/wydarzenies_helper.rb
module WydarzeniesHelper
end

app/views/wydarzenies/_form.html.erb
<%= form_for(@wydarzeny) do |f| %>
  <% if @wydarzeny.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wydarzeny.errors.count, "error") %> prohibited this wydarzeny from being saved:</h2>

      <ul>
      <% @wydarzeny.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nazwa %><br />
    <%= f.text_field :nazwa %>
  </div>
  <div class="field">
    <%= f.label :opis %><br />
    <%= f.text_area :opis %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wydarzenies/edit.html.erb
<h1>Editing wydarzeny</h1>

<%= render 'form' %>

<%= link_to 'Show', @wydarzeny %> |
<%= link_to 'Back', wydarzenies_path %>

app/views/wydarzenies/index.html.erb
<h1>Listing wydarzenies</h1>

<table>
  <tr>
    <th>Nazwa</th>
    <th>Opis</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wydarzenies.each do |wydarzeny| %>
  <tr>
    <td><%= wydarzeny.nazwa %></td>
    <td><%= wydarzeny.opis %></td>
    <td><%= link_to 'Show', wydarzeny %></td>
    <td><%= link_to 'Edit', edit_wydarzeny_path(wydarzeny) %></td>
    <td><%= link_to 'Destroy', wydarzeny, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wydarzenie', new_wydarzeny_path %>

app/views/wydarzenies/new.html.erb
<h1>New wydarzeny</h1>

<%= render 'form' %>

<%= link_to 'Back', wydarzenies_path %>

app/views/wydarzenies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nazwa:</b>
  <%= @wydarzeny.nazwa %>
</p>

<p>
  <b>Opis:</b>
  <%= @wydarzeny.opis %>
</p>
<p>
  <b>Autor:</b>
  <%= @wydarzeny.uzytkownik %>
</p>



<%= link_to 'Edit', edit_wydarzeny_path(@wydarzeny) %> |
<%= link_to 'Back', wydarzenies_path %>