config/routes.rb
Projekt::Application.routes.draw do
  resources :wydarzenies

  resources :kategoria

  resources :komentarzs

  resources :wpis

  resources :uzytkowniks

end

app/models/uzytkownik.rb
class Uzytkownik < ActiveRecord::Base
  
end

app/controllers/uzytkowniks_controller.rb
class UzytkowniksController < ApplicationController
  # GET /uzytkowniks
  # GET /uzytkowniks.json
  def index
    @uzytkowniks = Uzytkownik.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @uzytkowniks }
    end
  end

  # GET /uzytkowniks/1
  # GET /uzytkowniks/1.json
  def show
    @uzytkownik = Uzytkownik.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @uzytkownik }
    end
  end

  # GET /uzytkowniks/new
  # GET /uzytkowniks/new.json
  def new
    @uzytkownik = Uzytkownik.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @uzytkownik }
    end
  end

  # GET /uzytkowniks/1/edit
  def edit
    @uzytkownik = Uzytkownik.find(params[:id])
  end

  # POST /uzytkowniks
  # POST /uzytkowniks.json
  def create
    @uzytkownik = Uzytkownik.new(params[:uzytkownik])

    respond_to do |format|
      if @uzytkownik.save
        format.html { redirect_to @uzytkownik, notice: 'Uzytkownik was successfully created.' }
        format.json { render json: @uzytkownik, status: :created, location: @uzytkownik }
      else
        format.html { render action: "new" }
        format.json { render json: @uzytkownik.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /uzytkowniks/1
  # PUT /uzytkowniks/1.json
  def update
    @uzytkownik = Uzytkownik.find(params[:id])

    respond_to do |format|
      if @uzytkownik.update_attributes(params[:uzytkownik])
        format.html { redirect_to @uzytkownik, notice: 'Uzytkownik was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @uzytkownik.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uzytkowniks/1
  # DELETE /uzytkowniks/1.json
  def destroy
    @uzytkownik = Uzytkownik.find(params[:id])
    @uzytkownik.destroy

    respond_to do |format|
      format.html { redirect_to uzytkowniks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/uzytkowniks_helper.rb
module UzytkowniksHelper
end

app/views/uzytkowniks/_form.html.erb
<%= form_for(@uzytkownik) do |f| %>
  <% if @uzytkownik.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@uzytkownik.errors.count, "error") %> prohibited this uzytkownik from being saved:</h2>

      <ul>
      <% @uzytkownik.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %><br />
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :haslo %><br />
    <%= f.text_field :haslo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/uzytkowniks/edit.html.erb
<h1>Editing uzytkownik</h1>

<%= render 'form' %>

<%= link_to 'Show', @uzytkownik %> |
<%= link_to 'Back', uzytkowniks_path %>

app/views/uzytkowniks/index.html.erb
<h1>Listing uzytkowniks</h1>

<table>
  <tr>
    <th>Login</th>
    <th>Haslo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @uzytkowniks.each do |uzytkownik| %>
  <tr>
    <td><%= uzytkownik.login %></td>
    <td><%= uzytkownik.haslo %></td>
    <td><%= link_to 'Show', uzytkownik %></td>
    <td><%= link_to 'Edit', edit_uzytkownik_path(uzytkownik) %></td>
    <td><%= link_to 'Destroy', uzytkownik, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Uzytkownik', new_uzytkownik_path %>

app/views/uzytkowniks/new.html.erb
<h1>New uzytkownik</h1>

<%= render 'form' %>

<%= link_to 'Back', uzytkowniks_path %>

app/views/uzytkowniks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Login:</b>
  <%= @uzytkownik.login %>
</p>

<p>
  <b>Haslo:</b>
  <%= @uzytkownik.haslo %>
</p>


<%= link_to 'Edit', edit_uzytkownik_path(@uzytkownik) %> |
<%= link_to 'Back', uzytkowniks_path %>