config/routes.rb
Projekt::Application.routes.draw do
  resources :wydarzenies

  resources :kategoria

  resources :komentarzs

  resources :wpis

  resources :uzytkowniks

end

app/models/wpi.rb
class Wpi < ActiveRecord::Base
  belongs_to :uzytkownik
  attr_accessible :nazwa, :uzytkownik

end

app/controllers/wpis_controller.rb
class WpisController < ApplicationController
  before_filter :find_uzytkowniks, :only => [:new, :edit, :update, :create]
  # GET /wpis
  # GET /wpis.json
  def index
    @wpis = Wpi.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wpis }
    end
  end

  # GET /wpis/1
  # GET /wpis/1.json
  def show
    @wpi = Wpi.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wpi }
    end
  end

  # GET /wpis/new
  # GET /wpis/new.json
  def new
    @wpi = Wpi.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wpi }
    end
  end

  # GET /wpis/1/edit
  def edit
    @wpi = Wpi.find(params[:id])
  end

  # POST /wpis
  # POST /wpis.json
  def create
    @wpi = Wpi.new(params[:wpi])

    respond_to do |format|
      if @wpi.save
        format.html { redirect_to @wpi, notice: 'Wpi was successfully created.' }
        format.json { render json: @wpi, status: :created, location: @wpi }
      else
        format.html { render action: "new" }
        format.json { render json: @wpi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wpis/1
  # PUT /wpis/1.json
  def update
    @wpi = Wpi.find(params[:id])

    respond_to do |format|
      if @wpi.update_attributes(params[:wpi])
        format.html { redirect_to @wpi, notice: 'Wpi was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wpi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wpis/1
  # DELETE /wpis/1.json
  def destroy
    @wpi = Wpi.find(params[:id])
    @wpi.destroy

    respond_to do |format|
      format.html { redirect_to wpis_url }
      format.json { head :no_content }
    end
  end
protected
    def find_uzytkowniks
      @uzytkowniks = Uzytkownik.find(:all).map do |uzytkownik|
        [ uzytkownik.login, uzytkownik ]
      end
    end

end

app/helpers/wpis_helper.rb
module WpisHelper
end

app/views/wpis/_form.html.erb
<%= form_for(@wpi) do |f| %>
  <% if @wpi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wpi.errors.count, "error") %> prohibited this wpi from being saved:</h2>

      <ul>
      <% @wpi.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tytul %><br />
    <%= f.text_field :tytul %>
  </div>
  <div class="field">
    <%= f.label :tresc %><br />
    <%= f.text_area :tresc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wpis/edit.html.erb
<h1>Editing wpi</h1>

<%= render 'form' %>

<%= link_to 'Show', @wpi %> |
<%= link_to 'Back', wpis_path %>

app/views/wpis/index.html.erb
<h1>Spis wpisow</h1>

<table>
  <tr>
    <th>Tytul</th>
    <th>Tresc</th>
    <th>Autor</th>
    <th></th>
    <th></th>
  </tr>

<% @wpis.each do |wpi| %>
  <tr>
    <td><%= wpi.tytul %></td>
    <td><%= wpi.tresc %></td>
    <td><%= wpi.uzytkownik %></td>
    <td><%= link_to 'Show', wpi %></td>
    <td><%= link_to 'Edit', edit_wpi_path(wpi) %></td>
    <td><%= link_to 'Destroy', wpi, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wpi', new_wpi_path %>

app/views/wpis/new.html.erb
<h1>New wpi</h1>

<%= render 'form' %>

<%= link_to 'Back', wpis_path %>

app/views/wpis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tytul:</b>
  <%= @wpi.tytul %>
</p>

<p>
  <b>Tresc:</b>
  <%= @wpi.tresc %>
</p>


<%= link_to 'Edit', edit_wpi_path(@wpi) %> |
<%= link_to 'Back', wpis_path %>